name = "GTFSGraphs"
uuid = "f4d3b73b-4126-4014-bbe2-b5de87478027"
authors = ["James Mulhern"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
